/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AvatarSize } from "./components/avatar/avatar";
import { BadgeVariant } from "./components/badge/badge";
import { ButtonSize, ButtonVariant } from "./components/button/button";
import { Locale } from "./i18n/types";
import { SeparatorOrientation } from "./components/separator/separator";
export { AvatarSize } from "./components/avatar/avatar";
export { BadgeVariant } from "./components/badge/badge";
export { ButtonSize, ButtonVariant } from "./components/button/button";
export { Locale } from "./i18n/types";
export { SeparatorOrientation } from "./components/separator/separator";
export namespace Components {
    interface AppkitAccordion {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ""
         */
        "label": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface AppkitAccountButton {
        /**
          * @default ""
         */
        "address": string;
        /**
          * @default null
         */
        "balance": string | null;
        /**
          * @default "ETH"
         */
        "balanceSymbol": string;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default true
         */
        "showAddress": boolean;
        /**
          * @default false
         */
        "showBalance": boolean;
    }
    interface AppkitAlertDialog {
        /**
          * @default ""
         */
        "description": string;
        /**
          * @default ""
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface AppkitAvatar {
        /**
          * Alt text for image
          * @default ""
         */
        "alt": string;
        /**
          * Fallback text when image fails to load (e.g. initials)
          * @default ""
         */
        "fallback": string;
        /**
          * @default "default"
         */
        "size": AvatarSize;
        /**
          * Image URL
          * @default ""
         */
        "src": string;
    }
    interface AppkitBadge {
        /**
          * @default "default"
         */
        "variant": BadgeVariant;
    }
    interface AppkitButton {
        /**
          * Explicit aria-label (overrides i18n auto-label)
          * @default null
         */
        "ariaLabel": string | null;
        /**
          * Disable the button
          * @default false
         */
        "disabled": boolean;
        /**
          * Click event name to dispatch
          * @default "appkit-click"
         */
        "eventName": string;
        /**
          * Locale for i18n (aria-label fallback)
          * @default "en"
         */
        "locale": Locale;
        /**
          * Size preset (default, sm, lg, icon)
          * @default "default"
         */
        "size": ButtonSize;
        /**
          * Button type attribute
          * @default "button"
         */
        "type": "button" | "submit" | "reset";
        /**
          * Visual variant (default, destructive, outline, secondary, ghost, link)
          * @default "default"
         */
        "variant": ButtonVariant;
    }
    interface AppkitCard {
    }
    interface AppkitCardContent {
    }
    interface AppkitCardDescription {
    }
    interface AppkitCardFooter {
    }
    interface AppkitCardHeader {
    }
    interface AppkitCardTitle {
    }
    interface AppkitCheckbox {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ""
         */
        "label": string;
        /**
          * @default ""
         */
        "name": string;
        /**
          * @default "on"
         */
        "value": string;
    }
    interface AppkitCollapsible {
        /**
          * @default false
         */
        "open": boolean;
    }
    interface AppkitConnectButton {
        /**
          * @default ""
         */
        "address": string;
        /**
          * @default null
         */
        "balance": string | null;
        /**
          * @default "ETH"
         */
        "balanceSymbol": string;
        /**
          * @default false
         */
        "connected": boolean;
        /**
          * @default false
         */
        "connecting": boolean;
        /**
          * @default ""
         */
        "explorerLabel": string;
        /**
          * @default ""
         */
        "explorerUrl": string;
        /**
          * @default false
         */
        "isBalanceLoading": boolean;
        /**
          * @default false
         */
        "isMobile": boolean;
        /**
          * @default ""
         */
        "mobileWalletName": string;
        /**
          * @default null
         */
        "qrError": string | null;
        /**
          * @default false
         */
        "qrLoading": boolean;
        /**
          * @default null
         */
        "qrUri": string | null;
        /**
          * @default "[]"
         */
        "tokenBalancesJson": string;
        /**
          * @default "[]"
         */
        "walletsJson": string;
    }
    interface AppkitDialog {
        /**
          * @default ""
         */
        "heading": string;
        /**
          * @default false
         */
        "open": boolean;
    }
    interface AppkitDropdownMenu {
        /**
          * JSON string of MenuItem[]
          * @default "[]"
         */
        "itemsJson": string;
    }
    interface AppkitInput {
        /**
          * Autocomplete hint
          * @default "off"
         */
        "autocomplete": string;
        /**
          * Disable input
          * @default false
         */
        "disabled": boolean;
        /**
          * Invalid state
          * @default false
         */
        "invalid": boolean;
        /**
          * Max character length
         */
        "maxLength"?: number;
        /**
          * Name attribute (for forms)
          * @default ""
         */
        "name": string;
        /**
          * Placeholder text
          * @default ""
         */
        "placeholder": string;
        /**
          * Input type
          * @default "text"
         */
        "type": string;
        /**
          * Current value
          * @default ""
         */
        "value": string;
    }
    interface AppkitPopover {
        /**
          * @default false
         */
        "open": boolean;
        /**
          * @default "bottom"
         */
        "placement": "top" | "bottom" | "left" | "right";
    }
    interface AppkitProgress {
        /**
          * Accessible label
          * @default ""
         */
        "label": string;
        /**
          * Maximum value
          * @default 100
         */
        "max": number;
        /**
          * Progress value (0-100)
          * @default 0
         */
        "value": number;
    }
    interface AppkitScrollArea {
    }
    interface AppkitSelect {
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * JSON string of SelectOption[]
          * @default "[]"
         */
        "optionsJson": string;
        /**
          * @default "Select..."
         */
        "placeholder": string;
        /**
          * @default ""
         */
        "value": string;
    }
    interface AppkitSeparator {
        /**
          * When true, separator is purely visual (not announced by screen readers)
          * @default true
         */
        "decorative": boolean;
        /**
          * @default "horizontal"
         */
        "orientation": SeparatorOrientation;
    }
    interface AppkitSkeleton {
    }
    interface AppkitSwitch {
        /**
          * @default false
         */
        "checked": boolean;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default ""
         */
        "label": string;
    }
    interface AppkitTabs {
        /**
          * Currently selected tab id
          * @default ""
         */
        "selected": string;
        /**
          * JSON string of Tab[] — parsed internally
          * @default "[]"
         */
        "tabsJson": string;
    }
    interface AppkitToggleGroup {
        /**
          * JSON string of ToggleItem[]
          * @default "[]"
         */
        "itemsJson": string;
        /**
          * @default false
         */
        "multiple": boolean;
        /**
          * Comma-separated list of selected item IDs
          * @default []
         */
        "selected": string[];
    }
    interface AppkitTooltip {
        /**
          * @default ""
         */
        "content": string;
        /**
          * @default "top"
         */
        "placement": "top" | "bottom" | "left" | "right";
    }
}
export interface AppkitAccordionCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitAccordionElement;
}
export interface AppkitAlertDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitAlertDialogElement;
}
export interface AppkitCheckboxCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitCheckboxElement;
}
export interface AppkitCollapsibleCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitCollapsibleElement;
}
export interface AppkitConnectButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitConnectButtonElement;
}
export interface AppkitDialogCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitDialogElement;
}
export interface AppkitDropdownMenuCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitDropdownMenuElement;
}
export interface AppkitPopoverCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitPopoverElement;
}
export interface AppkitSelectCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitSelectElement;
}
export interface AppkitSwitchCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitSwitchElement;
}
export interface AppkitTabsCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitTabsElement;
}
export interface AppkitToggleGroupCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLAppkitToggleGroupElement;
}
declare global {
    interface HTMLAppkitAccordionElementEventMap {
        "appkitToggle": boolean;
    }
    interface HTMLAppkitAccordionElement extends Components.AppkitAccordion, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitAccordionElementEventMap>(type: K, listener: (this: HTMLAppkitAccordionElement, ev: AppkitAccordionCustomEvent<HTMLAppkitAccordionElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitAccordionElementEventMap>(type: K, listener: (this: HTMLAppkitAccordionElement, ev: AppkitAccordionCustomEvent<HTMLAppkitAccordionElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitAccordionElement: {
        prototype: HTMLAppkitAccordionElement;
        new (): HTMLAppkitAccordionElement;
    };
    interface HTMLAppkitAccountButtonElement extends Components.AppkitAccountButton, HTMLStencilElement {
    }
    var HTMLAppkitAccountButtonElement: {
        prototype: HTMLAppkitAccountButtonElement;
        new (): HTMLAppkitAccountButtonElement;
    };
    interface HTMLAppkitAlertDialogElementEventMap {
        "appkitClose": void;
        "appkitOpenChange": boolean;
    }
    interface HTMLAppkitAlertDialogElement extends Components.AppkitAlertDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitAlertDialogElementEventMap>(type: K, listener: (this: HTMLAppkitAlertDialogElement, ev: AppkitAlertDialogCustomEvent<HTMLAppkitAlertDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitAlertDialogElementEventMap>(type: K, listener: (this: HTMLAppkitAlertDialogElement, ev: AppkitAlertDialogCustomEvent<HTMLAppkitAlertDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitAlertDialogElement: {
        prototype: HTMLAppkitAlertDialogElement;
        new (): HTMLAppkitAlertDialogElement;
    };
    interface HTMLAppkitAvatarElement extends Components.AppkitAvatar, HTMLStencilElement {
    }
    var HTMLAppkitAvatarElement: {
        prototype: HTMLAppkitAvatarElement;
        new (): HTMLAppkitAvatarElement;
    };
    interface HTMLAppkitBadgeElement extends Components.AppkitBadge, HTMLStencilElement {
    }
    var HTMLAppkitBadgeElement: {
        prototype: HTMLAppkitBadgeElement;
        new (): HTMLAppkitBadgeElement;
    };
    interface HTMLAppkitButtonElement extends Components.AppkitButton, HTMLStencilElement {
    }
    var HTMLAppkitButtonElement: {
        prototype: HTMLAppkitButtonElement;
        new (): HTMLAppkitButtonElement;
    };
    interface HTMLAppkitCardElement extends Components.AppkitCard, HTMLStencilElement {
    }
    var HTMLAppkitCardElement: {
        prototype: HTMLAppkitCardElement;
        new (): HTMLAppkitCardElement;
    };
    interface HTMLAppkitCardContentElement extends Components.AppkitCardContent, HTMLStencilElement {
    }
    var HTMLAppkitCardContentElement: {
        prototype: HTMLAppkitCardContentElement;
        new (): HTMLAppkitCardContentElement;
    };
    interface HTMLAppkitCardDescriptionElement extends Components.AppkitCardDescription, HTMLStencilElement {
    }
    var HTMLAppkitCardDescriptionElement: {
        prototype: HTMLAppkitCardDescriptionElement;
        new (): HTMLAppkitCardDescriptionElement;
    };
    interface HTMLAppkitCardFooterElement extends Components.AppkitCardFooter, HTMLStencilElement {
    }
    var HTMLAppkitCardFooterElement: {
        prototype: HTMLAppkitCardFooterElement;
        new (): HTMLAppkitCardFooterElement;
    };
    interface HTMLAppkitCardHeaderElement extends Components.AppkitCardHeader, HTMLStencilElement {
    }
    var HTMLAppkitCardHeaderElement: {
        prototype: HTMLAppkitCardHeaderElement;
        new (): HTMLAppkitCardHeaderElement;
    };
    interface HTMLAppkitCardTitleElement extends Components.AppkitCardTitle, HTMLStencilElement {
    }
    var HTMLAppkitCardTitleElement: {
        prototype: HTMLAppkitCardTitleElement;
        new (): HTMLAppkitCardTitleElement;
    };
    interface HTMLAppkitCheckboxElementEventMap {
        "appkitChange": boolean;
    }
    interface HTMLAppkitCheckboxElement extends Components.AppkitCheckbox, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitCheckboxElementEventMap>(type: K, listener: (this: HTMLAppkitCheckboxElement, ev: AppkitCheckboxCustomEvent<HTMLAppkitCheckboxElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitCheckboxElementEventMap>(type: K, listener: (this: HTMLAppkitCheckboxElement, ev: AppkitCheckboxCustomEvent<HTMLAppkitCheckboxElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitCheckboxElement: {
        prototype: HTMLAppkitCheckboxElement;
        new (): HTMLAppkitCheckboxElement;
    };
    interface HTMLAppkitCollapsibleElementEventMap {
        "appkitToggle": boolean;
    }
    interface HTMLAppkitCollapsibleElement extends Components.AppkitCollapsible, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitCollapsibleElementEventMap>(type: K, listener: (this: HTMLAppkitCollapsibleElement, ev: AppkitCollapsibleCustomEvent<HTMLAppkitCollapsibleElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitCollapsibleElementEventMap>(type: K, listener: (this: HTMLAppkitCollapsibleElement, ev: AppkitCollapsibleCustomEvent<HTMLAppkitCollapsibleElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitCollapsibleElement: {
        prototype: HTMLAppkitCollapsibleElement;
        new (): HTMLAppkitCollapsibleElement;
    };
    interface HTMLAppkitConnectButtonElementEventMap {
        "appkitConnect": { kind: string; walletId?: string };
        "appkitDisconnect": void;
        "appkitStartPairing": void;
        "appkitRetry": void;
        "appkitMobileDeepLink": void;
        "appkitCopyAddress": string;
    }
    interface HTMLAppkitConnectButtonElement extends Components.AppkitConnectButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitConnectButtonElementEventMap>(type: K, listener: (this: HTMLAppkitConnectButtonElement, ev: AppkitConnectButtonCustomEvent<HTMLAppkitConnectButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitConnectButtonElementEventMap>(type: K, listener: (this: HTMLAppkitConnectButtonElement, ev: AppkitConnectButtonCustomEvent<HTMLAppkitConnectButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitConnectButtonElement: {
        prototype: HTMLAppkitConnectButtonElement;
        new (): HTMLAppkitConnectButtonElement;
    };
    interface HTMLAppkitDialogElementEventMap {
        "appkitClose": void;
        "appkitOpenChange": boolean;
    }
    interface HTMLAppkitDialogElement extends Components.AppkitDialog, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitDialogElementEventMap>(type: K, listener: (this: HTMLAppkitDialogElement, ev: AppkitDialogCustomEvent<HTMLAppkitDialogElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitDialogElementEventMap>(type: K, listener: (this: HTMLAppkitDialogElement, ev: AppkitDialogCustomEvent<HTMLAppkitDialogElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitDialogElement: {
        prototype: HTMLAppkitDialogElement;
        new (): HTMLAppkitDialogElement;
    };
    interface HTMLAppkitDropdownMenuElementEventMap {
        "appkitSelect": string;
    }
    interface HTMLAppkitDropdownMenuElement extends Components.AppkitDropdownMenu, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitDropdownMenuElementEventMap>(type: K, listener: (this: HTMLAppkitDropdownMenuElement, ev: AppkitDropdownMenuCustomEvent<HTMLAppkitDropdownMenuElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitDropdownMenuElementEventMap>(type: K, listener: (this: HTMLAppkitDropdownMenuElement, ev: AppkitDropdownMenuCustomEvent<HTMLAppkitDropdownMenuElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitDropdownMenuElement: {
        prototype: HTMLAppkitDropdownMenuElement;
        new (): HTMLAppkitDropdownMenuElement;
    };
    interface HTMLAppkitInputElement extends Components.AppkitInput, HTMLStencilElement {
    }
    var HTMLAppkitInputElement: {
        prototype: HTMLAppkitInputElement;
        new (): HTMLAppkitInputElement;
    };
    interface HTMLAppkitPopoverElementEventMap {
        "appkitOpenChange": boolean;
    }
    interface HTMLAppkitPopoverElement extends Components.AppkitPopover, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitPopoverElementEventMap>(type: K, listener: (this: HTMLAppkitPopoverElement, ev: AppkitPopoverCustomEvent<HTMLAppkitPopoverElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitPopoverElementEventMap>(type: K, listener: (this: HTMLAppkitPopoverElement, ev: AppkitPopoverCustomEvent<HTMLAppkitPopoverElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitPopoverElement: {
        prototype: HTMLAppkitPopoverElement;
        new (): HTMLAppkitPopoverElement;
    };
    interface HTMLAppkitProgressElement extends Components.AppkitProgress, HTMLStencilElement {
    }
    var HTMLAppkitProgressElement: {
        prototype: HTMLAppkitProgressElement;
        new (): HTMLAppkitProgressElement;
    };
    interface HTMLAppkitScrollAreaElement extends Components.AppkitScrollArea, HTMLStencilElement {
    }
    var HTMLAppkitScrollAreaElement: {
        prototype: HTMLAppkitScrollAreaElement;
        new (): HTMLAppkitScrollAreaElement;
    };
    interface HTMLAppkitSelectElementEventMap {
        "appkitChange": string;
    }
    interface HTMLAppkitSelectElement extends Components.AppkitSelect, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitSelectElementEventMap>(type: K, listener: (this: HTMLAppkitSelectElement, ev: AppkitSelectCustomEvent<HTMLAppkitSelectElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitSelectElementEventMap>(type: K, listener: (this: HTMLAppkitSelectElement, ev: AppkitSelectCustomEvent<HTMLAppkitSelectElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitSelectElement: {
        prototype: HTMLAppkitSelectElement;
        new (): HTMLAppkitSelectElement;
    };
    interface HTMLAppkitSeparatorElement extends Components.AppkitSeparator, HTMLStencilElement {
    }
    var HTMLAppkitSeparatorElement: {
        prototype: HTMLAppkitSeparatorElement;
        new (): HTMLAppkitSeparatorElement;
    };
    interface HTMLAppkitSkeletonElement extends Components.AppkitSkeleton, HTMLStencilElement {
    }
    var HTMLAppkitSkeletonElement: {
        prototype: HTMLAppkitSkeletonElement;
        new (): HTMLAppkitSkeletonElement;
    };
    interface HTMLAppkitSwitchElementEventMap {
        "appkitChange": boolean;
    }
    interface HTMLAppkitSwitchElement extends Components.AppkitSwitch, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitSwitchElementEventMap>(type: K, listener: (this: HTMLAppkitSwitchElement, ev: AppkitSwitchCustomEvent<HTMLAppkitSwitchElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitSwitchElementEventMap>(type: K, listener: (this: HTMLAppkitSwitchElement, ev: AppkitSwitchCustomEvent<HTMLAppkitSwitchElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitSwitchElement: {
        prototype: HTMLAppkitSwitchElement;
        new (): HTMLAppkitSwitchElement;
    };
    interface HTMLAppkitTabsElementEventMap {
        "appkitTabChange": string;
    }
    interface HTMLAppkitTabsElement extends Components.AppkitTabs, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitTabsElementEventMap>(type: K, listener: (this: HTMLAppkitTabsElement, ev: AppkitTabsCustomEvent<HTMLAppkitTabsElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitTabsElementEventMap>(type: K, listener: (this: HTMLAppkitTabsElement, ev: AppkitTabsCustomEvent<HTMLAppkitTabsElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitTabsElement: {
        prototype: HTMLAppkitTabsElement;
        new (): HTMLAppkitTabsElement;
    };
    interface HTMLAppkitToggleGroupElementEventMap {
        "appkitChange": string[];
    }
    interface HTMLAppkitToggleGroupElement extends Components.AppkitToggleGroup, HTMLStencilElement {
        addEventListener<K extends keyof HTMLAppkitToggleGroupElementEventMap>(type: K, listener: (this: HTMLAppkitToggleGroupElement, ev: AppkitToggleGroupCustomEvent<HTMLAppkitToggleGroupElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLAppkitToggleGroupElementEventMap>(type: K, listener: (this: HTMLAppkitToggleGroupElement, ev: AppkitToggleGroupCustomEvent<HTMLAppkitToggleGroupElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLAppkitToggleGroupElement: {
        prototype: HTMLAppkitToggleGroupElement;
        new (): HTMLAppkitToggleGroupElement;
    };
    interface HTMLAppkitTooltipElement extends Components.AppkitTooltip, HTMLStencilElement {
    }
    var HTMLAppkitTooltipElement: {
        prototype: HTMLAppkitTooltipElement;
        new (): HTMLAppkitTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "appkit-accordion": HTMLAppkitAccordionElement;
        "appkit-account-button": HTMLAppkitAccountButtonElement;
        "appkit-alert-dialog": HTMLAppkitAlertDialogElement;
        "appkit-avatar": HTMLAppkitAvatarElement;
        "appkit-badge": HTMLAppkitBadgeElement;
        "appkit-button": HTMLAppkitButtonElement;
        "appkit-card": HTMLAppkitCardElement;
        "appkit-card-content": HTMLAppkitCardContentElement;
        "appkit-card-description": HTMLAppkitCardDescriptionElement;
        "appkit-card-footer": HTMLAppkitCardFooterElement;
        "appkit-card-header": HTMLAppkitCardHeaderElement;
        "appkit-card-title": HTMLAppkitCardTitleElement;
        "appkit-checkbox": HTMLAppkitCheckboxElement;
        "appkit-collapsible": HTMLAppkitCollapsibleElement;
        "appkit-connect-button": HTMLAppkitConnectButtonElement;
        "appkit-dialog": HTMLAppkitDialogElement;
        "appkit-dropdown-menu": HTMLAppkitDropdownMenuElement;
        "appkit-input": HTMLAppkitInputElement;
        "appkit-popover": HTMLAppkitPopoverElement;
        "appkit-progress": HTMLAppkitProgressElement;
        "appkit-scroll-area": HTMLAppkitScrollAreaElement;
        "appkit-select": HTMLAppkitSelectElement;
        "appkit-separator": HTMLAppkitSeparatorElement;
        "appkit-skeleton": HTMLAppkitSkeletonElement;
        "appkit-switch": HTMLAppkitSwitchElement;
        "appkit-tabs": HTMLAppkitTabsElement;
        "appkit-toggle-group": HTMLAppkitToggleGroupElement;
        "appkit-tooltip": HTMLAppkitTooltipElement;
    }
}
declare namespace LocalJSX {
    interface AppkitAccordion {
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ""
         */
        "label"?: string;
        "onAppkitToggle"?: (event: AppkitAccordionCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface AppkitAccountButton {
        /**
          * @default ""
         */
        "address"?: string;
        /**
          * @default null
         */
        "balance"?: string | null;
        /**
          * @default "ETH"
         */
        "balanceSymbol"?: string;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default true
         */
        "showAddress"?: boolean;
        /**
          * @default false
         */
        "showBalance"?: boolean;
    }
    interface AppkitAlertDialog {
        /**
          * @default ""
         */
        "description"?: string;
        /**
          * @default ""
         */
        "heading"?: string;
        "onAppkitClose"?: (event: AppkitAlertDialogCustomEvent<void>) => void;
        "onAppkitOpenChange"?: (event: AppkitAlertDialogCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface AppkitAvatar {
        /**
          * Alt text for image
          * @default ""
         */
        "alt"?: string;
        /**
          * Fallback text when image fails to load (e.g. initials)
          * @default ""
         */
        "fallback"?: string;
        /**
          * @default "default"
         */
        "size"?: AvatarSize;
        /**
          * Image URL
          * @default ""
         */
        "src"?: string;
    }
    interface AppkitBadge {
        /**
          * @default "default"
         */
        "variant"?: BadgeVariant;
    }
    interface AppkitButton {
        /**
          * Explicit aria-label (overrides i18n auto-label)
          * @default null
         */
        "ariaLabel"?: string | null;
        /**
          * Disable the button
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Click event name to dispatch
          * @default "appkit-click"
         */
        "eventName"?: string;
        /**
          * Locale for i18n (aria-label fallback)
          * @default "en"
         */
        "locale"?: Locale;
        /**
          * Size preset (default, sm, lg, icon)
          * @default "default"
         */
        "size"?: ButtonSize;
        /**
          * Button type attribute
          * @default "button"
         */
        "type"?: "button" | "submit" | "reset";
        /**
          * Visual variant (default, destructive, outline, secondary, ghost, link)
          * @default "default"
         */
        "variant"?: ButtonVariant;
    }
    interface AppkitCard {
    }
    interface AppkitCardContent {
    }
    interface AppkitCardDescription {
    }
    interface AppkitCardFooter {
    }
    interface AppkitCardHeader {
    }
    interface AppkitCardTitle {
    }
    interface AppkitCheckbox {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ""
         */
        "label"?: string;
        /**
          * @default ""
         */
        "name"?: string;
        "onAppkitChange"?: (event: AppkitCheckboxCustomEvent<boolean>) => void;
        /**
          * @default "on"
         */
        "value"?: string;
    }
    interface AppkitCollapsible {
        "onAppkitToggle"?: (event: AppkitCollapsibleCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface AppkitConnectButton {
        /**
          * @default ""
         */
        "address"?: string;
        /**
          * @default null
         */
        "balance"?: string | null;
        /**
          * @default "ETH"
         */
        "balanceSymbol"?: string;
        /**
          * @default false
         */
        "connected"?: boolean;
        /**
          * @default false
         */
        "connecting"?: boolean;
        /**
          * @default ""
         */
        "explorerLabel"?: string;
        /**
          * @default ""
         */
        "explorerUrl"?: string;
        /**
          * @default false
         */
        "isBalanceLoading"?: boolean;
        /**
          * @default false
         */
        "isMobile"?: boolean;
        /**
          * @default ""
         */
        "mobileWalletName"?: string;
        "onAppkitConnect"?: (event: AppkitConnectButtonCustomEvent<{ kind: string; walletId?: string }>) => void;
        "onAppkitCopyAddress"?: (event: AppkitConnectButtonCustomEvent<string>) => void;
        "onAppkitDisconnect"?: (event: AppkitConnectButtonCustomEvent<void>) => void;
        "onAppkitMobileDeepLink"?: (event: AppkitConnectButtonCustomEvent<void>) => void;
        "onAppkitRetry"?: (event: AppkitConnectButtonCustomEvent<void>) => void;
        "onAppkitStartPairing"?: (event: AppkitConnectButtonCustomEvent<void>) => void;
        /**
          * @default null
         */
        "qrError"?: string | null;
        /**
          * @default false
         */
        "qrLoading"?: boolean;
        /**
          * @default null
         */
        "qrUri"?: string | null;
        /**
          * @default "[]"
         */
        "tokenBalancesJson"?: string;
        /**
          * @default "[]"
         */
        "walletsJson"?: string;
    }
    interface AppkitDialog {
        /**
          * @default ""
         */
        "heading"?: string;
        /**
          * Emitted when dialog is closed (Escape, backdrop click, or close button)
         */
        "onAppkitClose"?: (event: AppkitDialogCustomEvent<void>) => void;
        "onAppkitOpenChange"?: (event: AppkitDialogCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
    }
    interface AppkitDropdownMenu {
        /**
          * JSON string of MenuItem[]
          * @default "[]"
         */
        "itemsJson"?: string;
        "onAppkitSelect"?: (event: AppkitDropdownMenuCustomEvent<string>) => void;
    }
    interface AppkitInput {
        /**
          * Autocomplete hint
          * @default "off"
         */
        "autocomplete"?: string;
        /**
          * Disable input
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Invalid state
          * @default false
         */
        "invalid"?: boolean;
        /**
          * Max character length
         */
        "maxLength"?: number;
        /**
          * Name attribute (for forms)
          * @default ""
         */
        "name"?: string;
        /**
          * Placeholder text
          * @default ""
         */
        "placeholder"?: string;
        /**
          * Input type
          * @default "text"
         */
        "type"?: string;
        /**
          * Current value
          * @default ""
         */
        "value"?: string;
    }
    interface AppkitPopover {
        "onAppkitOpenChange"?: (event: AppkitPopoverCustomEvent<boolean>) => void;
        /**
          * @default false
         */
        "open"?: boolean;
        /**
          * @default "bottom"
         */
        "placement"?: "top" | "bottom" | "left" | "right";
    }
    interface AppkitProgress {
        /**
          * Accessible label
          * @default ""
         */
        "label"?: string;
        /**
          * Maximum value
          * @default 100
         */
        "max"?: number;
        /**
          * Progress value (0-100)
          * @default 0
         */
        "value"?: number;
    }
    interface AppkitScrollArea {
    }
    interface AppkitSelect {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "onAppkitChange"?: (event: AppkitSelectCustomEvent<string>) => void;
        /**
          * JSON string of SelectOption[]
          * @default "[]"
         */
        "optionsJson"?: string;
        /**
          * @default "Select..."
         */
        "placeholder"?: string;
        /**
          * @default ""
         */
        "value"?: string;
    }
    interface AppkitSeparator {
        /**
          * When true, separator is purely visual (not announced by screen readers)
          * @default true
         */
        "decorative"?: boolean;
        /**
          * @default "horizontal"
         */
        "orientation"?: SeparatorOrientation;
    }
    interface AppkitSkeleton {
    }
    interface AppkitSwitch {
        /**
          * @default false
         */
        "checked"?: boolean;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default ""
         */
        "label"?: string;
        "onAppkitChange"?: (event: AppkitSwitchCustomEvent<boolean>) => void;
    }
    interface AppkitTabs {
        "onAppkitTabChange"?: (event: AppkitTabsCustomEvent<string>) => void;
        /**
          * Currently selected tab id
          * @default ""
         */
        "selected"?: string;
        /**
          * JSON string of Tab[] — parsed internally
          * @default "[]"
         */
        "tabsJson"?: string;
    }
    interface AppkitToggleGroup {
        /**
          * JSON string of ToggleItem[]
          * @default "[]"
         */
        "itemsJson"?: string;
        /**
          * @default false
         */
        "multiple"?: boolean;
        "onAppkitChange"?: (event: AppkitToggleGroupCustomEvent<string[]>) => void;
        /**
          * Comma-separated list of selected item IDs
          * @default []
         */
        "selected"?: string[];
    }
    interface AppkitTooltip {
        /**
          * @default ""
         */
        "content"?: string;
        /**
          * @default "top"
         */
        "placement"?: "top" | "bottom" | "left" | "right";
    }

    interface AppkitAccordionAttributes {
        "label": string;
        "open": boolean;
        "disabled": boolean;
    }
    interface AppkitAccountButtonAttributes {
        "address": string;
        "balance": string | null;
        "balanceSymbol": string;
        "showAddress": boolean;
        "showBalance": boolean;
        "disabled": boolean;
    }
    interface AppkitAlertDialogAttributes {
        "open": boolean;
        "heading": string;
        "description": string;
    }
    interface AppkitAvatarAttributes {
        "size": AvatarSize;
        "src": string;
        "alt": string;
        "fallback": string;
    }
    interface AppkitBadgeAttributes {
        "variant": BadgeVariant;
    }
    interface AppkitButtonAttributes {
        "variant": ButtonVariant;
        "size": ButtonSize;
        "disabled": boolean;
        "type": "button" | "submit" | "reset";
        "locale": Locale;
        "ariaLabel": string | null;
        "eventName": string;
    }
    interface AppkitCheckboxAttributes {
        "checked": boolean;
        "disabled": boolean;
        "label": string;
        "name": string;
        "value": string;
    }
    interface AppkitCollapsibleAttributes {
        "open": boolean;
    }
    interface AppkitConnectButtonAttributes {
        "connected": boolean;
        "connecting": boolean;
        "address": string;
        "balance": string | null;
        "balanceSymbol": string;
        "isBalanceLoading": boolean;
        "tokenBalancesJson": string;
        "explorerUrl": string;
        "explorerLabel": string;
        "walletsJson": string;
        "isMobile": boolean;
        "mobileWalletName": string;
        "qrUri": string | null;
        "qrLoading": boolean;
        "qrError": string | null;
    }
    interface AppkitDialogAttributes {
        "open": boolean;
        "heading": string;
    }
    interface AppkitDropdownMenuAttributes {
        "itemsJson": string;
    }
    interface AppkitInputAttributes {
        "type": string;
        "placeholder": string;
        "value": string;
        "disabled": boolean;
        "invalid": boolean;
        "name": string;
        "autocomplete": string;
        "maxLength": number;
    }
    interface AppkitPopoverAttributes {
        "open": boolean;
        "placement": "top" | "bottom" | "left" | "right";
    }
    interface AppkitProgressAttributes {
        "value": number;
        "max": number;
        "label": string;
    }
    interface AppkitSelectAttributes {
        "optionsJson": string;
        "value": string;
        "placeholder": string;
        "disabled": boolean;
    }
    interface AppkitSeparatorAttributes {
        "orientation": SeparatorOrientation;
        "decorative": boolean;
    }
    interface AppkitSwitchAttributes {
        "checked": boolean;
        "disabled": boolean;
        "label": string;
    }
    interface AppkitTabsAttributes {
        "tabsJson": string;
        "selected": string;
    }
    interface AppkitToggleGroupAttributes {
        "itemsJson": string;
        "multiple": boolean;
    }
    interface AppkitTooltipAttributes {
        "content": string;
        "placement": "top" | "bottom" | "left" | "right";
    }

    interface IntrinsicElements {
        "appkit-accordion": Omit<AppkitAccordion, keyof AppkitAccordionAttributes> & { [K in keyof AppkitAccordion & keyof AppkitAccordionAttributes]?: AppkitAccordion[K] } & { [K in keyof AppkitAccordion & keyof AppkitAccordionAttributes as `attr:${K}`]?: AppkitAccordionAttributes[K] } & { [K in keyof AppkitAccordion & keyof AppkitAccordionAttributes as `prop:${K}`]?: AppkitAccordion[K] };
        "appkit-account-button": Omit<AppkitAccountButton, keyof AppkitAccountButtonAttributes> & { [K in keyof AppkitAccountButton & keyof AppkitAccountButtonAttributes]?: AppkitAccountButton[K] } & { [K in keyof AppkitAccountButton & keyof AppkitAccountButtonAttributes as `attr:${K}`]?: AppkitAccountButtonAttributes[K] } & { [K in keyof AppkitAccountButton & keyof AppkitAccountButtonAttributes as `prop:${K}`]?: AppkitAccountButton[K] };
        "appkit-alert-dialog": Omit<AppkitAlertDialog, keyof AppkitAlertDialogAttributes> & { [K in keyof AppkitAlertDialog & keyof AppkitAlertDialogAttributes]?: AppkitAlertDialog[K] } & { [K in keyof AppkitAlertDialog & keyof AppkitAlertDialogAttributes as `attr:${K}`]?: AppkitAlertDialogAttributes[K] } & { [K in keyof AppkitAlertDialog & keyof AppkitAlertDialogAttributes as `prop:${K}`]?: AppkitAlertDialog[K] };
        "appkit-avatar": Omit<AppkitAvatar, keyof AppkitAvatarAttributes> & { [K in keyof AppkitAvatar & keyof AppkitAvatarAttributes]?: AppkitAvatar[K] } & { [K in keyof AppkitAvatar & keyof AppkitAvatarAttributes as `attr:${K}`]?: AppkitAvatarAttributes[K] } & { [K in keyof AppkitAvatar & keyof AppkitAvatarAttributes as `prop:${K}`]?: AppkitAvatar[K] };
        "appkit-badge": Omit<AppkitBadge, keyof AppkitBadgeAttributes> & { [K in keyof AppkitBadge & keyof AppkitBadgeAttributes]?: AppkitBadge[K] } & { [K in keyof AppkitBadge & keyof AppkitBadgeAttributes as `attr:${K}`]?: AppkitBadgeAttributes[K] } & { [K in keyof AppkitBadge & keyof AppkitBadgeAttributes as `prop:${K}`]?: AppkitBadge[K] };
        "appkit-button": Omit<AppkitButton, keyof AppkitButtonAttributes> & { [K in keyof AppkitButton & keyof AppkitButtonAttributes]?: AppkitButton[K] } & { [K in keyof AppkitButton & keyof AppkitButtonAttributes as `attr:${K}`]?: AppkitButtonAttributes[K] } & { [K in keyof AppkitButton & keyof AppkitButtonAttributes as `prop:${K}`]?: AppkitButton[K] };
        "appkit-card": AppkitCard;
        "appkit-card-content": AppkitCardContent;
        "appkit-card-description": AppkitCardDescription;
        "appkit-card-footer": AppkitCardFooter;
        "appkit-card-header": AppkitCardHeader;
        "appkit-card-title": AppkitCardTitle;
        "appkit-checkbox": Omit<AppkitCheckbox, keyof AppkitCheckboxAttributes> & { [K in keyof AppkitCheckbox & keyof AppkitCheckboxAttributes]?: AppkitCheckbox[K] } & { [K in keyof AppkitCheckbox & keyof AppkitCheckboxAttributes as `attr:${K}`]?: AppkitCheckboxAttributes[K] } & { [K in keyof AppkitCheckbox & keyof AppkitCheckboxAttributes as `prop:${K}`]?: AppkitCheckbox[K] };
        "appkit-collapsible": Omit<AppkitCollapsible, keyof AppkitCollapsibleAttributes> & { [K in keyof AppkitCollapsible & keyof AppkitCollapsibleAttributes]?: AppkitCollapsible[K] } & { [K in keyof AppkitCollapsible & keyof AppkitCollapsibleAttributes as `attr:${K}`]?: AppkitCollapsibleAttributes[K] } & { [K in keyof AppkitCollapsible & keyof AppkitCollapsibleAttributes as `prop:${K}`]?: AppkitCollapsible[K] };
        "appkit-connect-button": Omit<AppkitConnectButton, keyof AppkitConnectButtonAttributes> & { [K in keyof AppkitConnectButton & keyof AppkitConnectButtonAttributes]?: AppkitConnectButton[K] } & { [K in keyof AppkitConnectButton & keyof AppkitConnectButtonAttributes as `attr:${K}`]?: AppkitConnectButtonAttributes[K] } & { [K in keyof AppkitConnectButton & keyof AppkitConnectButtonAttributes as `prop:${K}`]?: AppkitConnectButton[K] };
        "appkit-dialog": Omit<AppkitDialog, keyof AppkitDialogAttributes> & { [K in keyof AppkitDialog & keyof AppkitDialogAttributes]?: AppkitDialog[K] } & { [K in keyof AppkitDialog & keyof AppkitDialogAttributes as `attr:${K}`]?: AppkitDialogAttributes[K] } & { [K in keyof AppkitDialog & keyof AppkitDialogAttributes as `prop:${K}`]?: AppkitDialog[K] };
        "appkit-dropdown-menu": Omit<AppkitDropdownMenu, keyof AppkitDropdownMenuAttributes> & { [K in keyof AppkitDropdownMenu & keyof AppkitDropdownMenuAttributes]?: AppkitDropdownMenu[K] } & { [K in keyof AppkitDropdownMenu & keyof AppkitDropdownMenuAttributes as `attr:${K}`]?: AppkitDropdownMenuAttributes[K] } & { [K in keyof AppkitDropdownMenu & keyof AppkitDropdownMenuAttributes as `prop:${K}`]?: AppkitDropdownMenu[K] };
        "appkit-input": Omit<AppkitInput, keyof AppkitInputAttributes> & { [K in keyof AppkitInput & keyof AppkitInputAttributes]?: AppkitInput[K] } & { [K in keyof AppkitInput & keyof AppkitInputAttributes as `attr:${K}`]?: AppkitInputAttributes[K] } & { [K in keyof AppkitInput & keyof AppkitInputAttributes as `prop:${K}`]?: AppkitInput[K] };
        "appkit-popover": Omit<AppkitPopover, keyof AppkitPopoverAttributes> & { [K in keyof AppkitPopover & keyof AppkitPopoverAttributes]?: AppkitPopover[K] } & { [K in keyof AppkitPopover & keyof AppkitPopoverAttributes as `attr:${K}`]?: AppkitPopoverAttributes[K] } & { [K in keyof AppkitPopover & keyof AppkitPopoverAttributes as `prop:${K}`]?: AppkitPopover[K] };
        "appkit-progress": Omit<AppkitProgress, keyof AppkitProgressAttributes> & { [K in keyof AppkitProgress & keyof AppkitProgressAttributes]?: AppkitProgress[K] } & { [K in keyof AppkitProgress & keyof AppkitProgressAttributes as `attr:${K}`]?: AppkitProgressAttributes[K] } & { [K in keyof AppkitProgress & keyof AppkitProgressAttributes as `prop:${K}`]?: AppkitProgress[K] };
        "appkit-scroll-area": AppkitScrollArea;
        "appkit-select": Omit<AppkitSelect, keyof AppkitSelectAttributes> & { [K in keyof AppkitSelect & keyof AppkitSelectAttributes]?: AppkitSelect[K] } & { [K in keyof AppkitSelect & keyof AppkitSelectAttributes as `attr:${K}`]?: AppkitSelectAttributes[K] } & { [K in keyof AppkitSelect & keyof AppkitSelectAttributes as `prop:${K}`]?: AppkitSelect[K] };
        "appkit-separator": Omit<AppkitSeparator, keyof AppkitSeparatorAttributes> & { [K in keyof AppkitSeparator & keyof AppkitSeparatorAttributes]?: AppkitSeparator[K] } & { [K in keyof AppkitSeparator & keyof AppkitSeparatorAttributes as `attr:${K}`]?: AppkitSeparatorAttributes[K] } & { [K in keyof AppkitSeparator & keyof AppkitSeparatorAttributes as `prop:${K}`]?: AppkitSeparator[K] };
        "appkit-skeleton": AppkitSkeleton;
        "appkit-switch": Omit<AppkitSwitch, keyof AppkitSwitchAttributes> & { [K in keyof AppkitSwitch & keyof AppkitSwitchAttributes]?: AppkitSwitch[K] } & { [K in keyof AppkitSwitch & keyof AppkitSwitchAttributes as `attr:${K}`]?: AppkitSwitchAttributes[K] } & { [K in keyof AppkitSwitch & keyof AppkitSwitchAttributes as `prop:${K}`]?: AppkitSwitch[K] };
        "appkit-tabs": Omit<AppkitTabs, keyof AppkitTabsAttributes> & { [K in keyof AppkitTabs & keyof AppkitTabsAttributes]?: AppkitTabs[K] } & { [K in keyof AppkitTabs & keyof AppkitTabsAttributes as `attr:${K}`]?: AppkitTabsAttributes[K] } & { [K in keyof AppkitTabs & keyof AppkitTabsAttributes as `prop:${K}`]?: AppkitTabs[K] };
        "appkit-toggle-group": Omit<AppkitToggleGroup, keyof AppkitToggleGroupAttributes> & { [K in keyof AppkitToggleGroup & keyof AppkitToggleGroupAttributes]?: AppkitToggleGroup[K] } & { [K in keyof AppkitToggleGroup & keyof AppkitToggleGroupAttributes as `attr:${K}`]?: AppkitToggleGroupAttributes[K] } & { [K in keyof AppkitToggleGroup & keyof AppkitToggleGroupAttributes as `prop:${K}`]?: AppkitToggleGroup[K] };
        "appkit-tooltip": Omit<AppkitTooltip, keyof AppkitTooltipAttributes> & { [K in keyof AppkitTooltip & keyof AppkitTooltipAttributes]?: AppkitTooltip[K] } & { [K in keyof AppkitTooltip & keyof AppkitTooltipAttributes as `attr:${K}`]?: AppkitTooltipAttributes[K] } & { [K in keyof AppkitTooltip & keyof AppkitTooltipAttributes as `prop:${K}`]?: AppkitTooltip[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "appkit-accordion": LocalJSX.IntrinsicElements["appkit-accordion"] & JSXBase.HTMLAttributes<HTMLAppkitAccordionElement>;
            "appkit-account-button": LocalJSX.IntrinsicElements["appkit-account-button"] & JSXBase.HTMLAttributes<HTMLAppkitAccountButtonElement>;
            "appkit-alert-dialog": LocalJSX.IntrinsicElements["appkit-alert-dialog"] & JSXBase.HTMLAttributes<HTMLAppkitAlertDialogElement>;
            "appkit-avatar": LocalJSX.IntrinsicElements["appkit-avatar"] & JSXBase.HTMLAttributes<HTMLAppkitAvatarElement>;
            "appkit-badge": LocalJSX.IntrinsicElements["appkit-badge"] & JSXBase.HTMLAttributes<HTMLAppkitBadgeElement>;
            "appkit-button": LocalJSX.IntrinsicElements["appkit-button"] & JSXBase.HTMLAttributes<HTMLAppkitButtonElement>;
            "appkit-card": LocalJSX.IntrinsicElements["appkit-card"] & JSXBase.HTMLAttributes<HTMLAppkitCardElement>;
            "appkit-card-content": LocalJSX.IntrinsicElements["appkit-card-content"] & JSXBase.HTMLAttributes<HTMLAppkitCardContentElement>;
            "appkit-card-description": LocalJSX.IntrinsicElements["appkit-card-description"] & JSXBase.HTMLAttributes<HTMLAppkitCardDescriptionElement>;
            "appkit-card-footer": LocalJSX.IntrinsicElements["appkit-card-footer"] & JSXBase.HTMLAttributes<HTMLAppkitCardFooterElement>;
            "appkit-card-header": LocalJSX.IntrinsicElements["appkit-card-header"] & JSXBase.HTMLAttributes<HTMLAppkitCardHeaderElement>;
            "appkit-card-title": LocalJSX.IntrinsicElements["appkit-card-title"] & JSXBase.HTMLAttributes<HTMLAppkitCardTitleElement>;
            "appkit-checkbox": LocalJSX.IntrinsicElements["appkit-checkbox"] & JSXBase.HTMLAttributes<HTMLAppkitCheckboxElement>;
            "appkit-collapsible": LocalJSX.IntrinsicElements["appkit-collapsible"] & JSXBase.HTMLAttributes<HTMLAppkitCollapsibleElement>;
            "appkit-connect-button": LocalJSX.IntrinsicElements["appkit-connect-button"] & JSXBase.HTMLAttributes<HTMLAppkitConnectButtonElement>;
            "appkit-dialog": LocalJSX.IntrinsicElements["appkit-dialog"] & JSXBase.HTMLAttributes<HTMLAppkitDialogElement>;
            "appkit-dropdown-menu": LocalJSX.IntrinsicElements["appkit-dropdown-menu"] & JSXBase.HTMLAttributes<HTMLAppkitDropdownMenuElement>;
            "appkit-input": LocalJSX.IntrinsicElements["appkit-input"] & JSXBase.HTMLAttributes<HTMLAppkitInputElement>;
            "appkit-popover": LocalJSX.IntrinsicElements["appkit-popover"] & JSXBase.HTMLAttributes<HTMLAppkitPopoverElement>;
            "appkit-progress": LocalJSX.IntrinsicElements["appkit-progress"] & JSXBase.HTMLAttributes<HTMLAppkitProgressElement>;
            "appkit-scroll-area": LocalJSX.IntrinsicElements["appkit-scroll-area"] & JSXBase.HTMLAttributes<HTMLAppkitScrollAreaElement>;
            "appkit-select": LocalJSX.IntrinsicElements["appkit-select"] & JSXBase.HTMLAttributes<HTMLAppkitSelectElement>;
            "appkit-separator": LocalJSX.IntrinsicElements["appkit-separator"] & JSXBase.HTMLAttributes<HTMLAppkitSeparatorElement>;
            "appkit-skeleton": LocalJSX.IntrinsicElements["appkit-skeleton"] & JSXBase.HTMLAttributes<HTMLAppkitSkeletonElement>;
            "appkit-switch": LocalJSX.IntrinsicElements["appkit-switch"] & JSXBase.HTMLAttributes<HTMLAppkitSwitchElement>;
            "appkit-tabs": LocalJSX.IntrinsicElements["appkit-tabs"] & JSXBase.HTMLAttributes<HTMLAppkitTabsElement>;
            "appkit-toggle-group": LocalJSX.IntrinsicElements["appkit-toggle-group"] & JSXBase.HTMLAttributes<HTMLAppkitToggleGroupElement>;
            "appkit-tooltip": LocalJSX.IntrinsicElements["appkit-tooltip"] & JSXBase.HTMLAttributes<HTMLAppkitTooltipElement>;
        }
    }
}
