packages:
  - 'packages/*'
link-workspace-packages: true
prefer-workspace-packages: true
shamefullyHoist: true
minimumReleaseAge: 0
allowBuilds:
  '@reown/appkit': set this to true or false
  '@swc/core': true
  bufferutil: true
  esbuild: true
  keccak: true
  msw: true
  puppeteer: true
  sharp: true
  unrs-resolver: true
  utf-8-validate: true
  workerd: true
